"""
state.py

Shared LangGraph state used by every agent.

The state acts as the application's shared memory while the graph
is executing.

Used by
--------
graph.py
planner.py
future specialist agents
"""
from __future__ import annotations

from typing import Any, TypedDict, Annotated, NotRequired

from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage


class GraphState(TypedDict):
    """
    Shared state passed between LangGraph nodes.

    Attributes
    ----------
    messages:
        Conversation history.
    company:
        Company name extracted from user input.
    task:
        Planner decision.
    final_report:
        Final response generated by the graph.
    dcf_forecast_input:
        Financial inputs required for a DCF forecast, supplied as a
        mapping compatible with DCFForecastInput.
    dcf_assumptions:
        DCF assumptions supplied as a mapping compatible with
        DCFAssumptions.
    dcf_wacc_inputs:
        Optional inputs for calculating WACC from market data.
    dcf_sensitivity_inputs:
        Optional WACC and terminal-growth scenario lists.
    dcf_analysis:
        Structured DCF outputs produced by the DCF Agent.
    """
    messages: Annotated[list[BaseMessage], add_messages]
    company: str
    task: str
    news: str
    final_report: str
    dcf_forecast_input: NotRequired[dict[str, Any]]
    dcf_assumptions: NotRequired[dict[str, Any]]
    dcf_wacc_inputs: NotRequired[dict[str, float]]
    dcf_sensitivity_inputs: NotRequired[dict[str, list[float]]]
    dcf_analysis: NotRequired[dict[str, Any]]
