"""
state.py

Shared LangGraph state used by every agent.

The state acts as the application's shared memory while the graph
is executing.

Used by
--------
graph.py
planner.py
future specialist agents
"""
from __future__ import annotations

from typing import TypedDict, Annotated

from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage


class GraphState(TypedDict):
    """
    Shared state passed between LangGraph nodes.

    Attributes
    ----------
    messages:
        Conversation history.
    company:
        Company name extracted from user input.
    task:
        Planner decision.
    final_report:
        Final response generated by the graph.
    """
    messages: Annotated[list[BaseMessage], add_messages]
    company: str
    task: str
    final_report: str
