"""
conversation_store.py

Laptop-local, SQLite-backed conversation history.
"""

from __future__ import annotations

import logging
import sqlite3
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path

from langchain_core.messages import AIMessage, BaseMessage, HumanMessage

from config.settings import MEMORY_DB_PATH, MEMORY_MAX_MESSAGES

logger = logging.getLogger(__name__)


class ConversationMemory:
    """Persist and retrieve bounded conversation history in local SQLite."""

    def __init__(
        self,
        db_path: Path = MEMORY_DB_PATH,
        max_messages: int = MEMORY_MAX_MESSAGES,
    ) -> None:
        """Initialize the local conversation store.

        Args:
            db_path: Path to the SQLite file on the laptop.
            max_messages: Maximum recent messages returned per conversation.

        Raises:
            ValueError: If the history limit is less than two.
        """
        if max_messages < 2:
            raise ValueError("max_messages must be at least two.")

        self.db_path = Path(db_path)
        self.max_messages = max_messages
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._initialize_database()

    @contextmanager
    def _connection(self) -> Iterator[sqlite3.Connection]:
        """Open, commit, and reliably close a local SQLite connection."""
        connection = sqlite3.connect(self.db_path, timeout=5.0)
        connection.row_factory = sqlite3.Row
        try:
            yield connection
            connection.commit()
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()

    def _initialize_database(self) -> None:
        """Create the conversation table when the local database is new."""
        with self._connection() as connection:
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS conversation_messages (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    conversation_id TEXT NOT NULL,
                    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
                    content TEXT NOT NULL,
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
            connection.execute(
                """
                CREATE INDEX IF NOT EXISTS
                    idx_conversation_messages_conversation_id
                ON conversation_messages (conversation_id, id)
                """
            )

    def load_messages(self, conversation_id: str) -> list[BaseMessage]:
        """Load the most recent messages for a conversation.

        Args:
            conversation_id: Stable local conversation identifier.

        Returns:
            Recent human and assistant messages in chronological order.

        Raises:
            ValueError: If the conversation identifier is blank.
        """
        normalized_id = conversation_id.strip()
        if not normalized_id:
            raise ValueError("conversation_id cannot be empty.")

        with self._connection() as connection:
            rows = connection.execute(
                """
                SELECT role, content
                FROM conversation_messages
                WHERE conversation_id = ?
                ORDER BY id DESC
                LIMIT ?
                """,
                (normalized_id, self.max_messages),
            ).fetchall()

        messages: list[BaseMessage] = []
        for row in reversed(rows):
            if row["role"] == "user":
                messages.append(HumanMessage(content=row["content"]))
            else:
                messages.append(AIMessage(content=row["content"]))
        # Keep exchanges intact if an odd limit cuts through a user/assistant
        # pair and the oldest retained row is an assistant response.
        if messages and isinstance(messages[0], AIMessage):
            messages.pop(0)
        return messages

    def save_turn(
        self,
        conversation_id: str,
        user_message: str,
        assistant_message: str,
    ) -> None:
        """Persist one completed user/assistant exchange atomically.

        Args:
            conversation_id: Stable local conversation identifier.
            user_message: User's message text.
            assistant_message: Final response generated by the graph.

        Raises:
            ValueError: If the identifier or either message is blank.
        """
        normalized_id = conversation_id.strip()
        if not normalized_id:
            raise ValueError("conversation_id cannot be empty.")
        if not user_message.strip():
            raise ValueError("user_message cannot be empty.")
        if not assistant_message.strip():
            raise ValueError("assistant_message cannot be empty.")

        with self._connection() as connection:
            connection.executemany(
                """
                INSERT INTO conversation_messages
                    (conversation_id, role, content)
                VALUES (?, ?, ?)
                """,
                [
                    (normalized_id, "user", user_message),
                    (normalized_id, "assistant", assistant_message),
                ],
            )
        logger.info("Saved a local conversation turn for %s", normalized_id)
