"""
rag_chain.py

RAG chain for answering questions using annual-report context.

Responsibilities
----------------
- Retrieve relevant annual-report documents.
- Build grounded context from retrieved documents.
- Send the context and user question to the Groq LLM.
- Return a grounded answer.

Used by
--------
agents/rag_agent.py
"""

from __future__ import annotations

import logging

from langchain_core.messages import HumanMessage, SystemMessage

from config.llm import llm
from rag.retriever import retrieve_documents

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """
You are an institutional equity research assistant.

Answer the user's question using ONLY the information provided
in the annual-report context.

Rules:
1. Do not invent facts.
2. Do not use outside knowledge.
3. If the context does not contain enough information, say:
   "The annual report does not provide enough information to answer this."
4. Give a clear and concise answer.
5. Preserve important numbers, dates, and financial facts.
6. When possible, mention the relevant page number from the context.
"""

def build_context(documents:list) ->str:
    """
    Convert retrieved documents into LLM-readable context.

    Args:
        documents: Documents retrieved from the vector store.

    Returns:
        Formatted annual-report context.
    """
    context_parts = []

    for document in documents:
        source = document.metadata.get("source", "unknown source")
        page = document.metadata.get("page", "unknown page")

        context_parts.append(
            f"Source: {source}\n"
            f"Page: {page}\n"
            f"Content:\n{document.page_content}"
        )
    return "\n\n---\n\n".join(context_parts)

def answer_question(question:str, k:int=5) ->str:
    """
    Answer a question using retrieved annual-report context.

    Args:
        question: User's question about the annual report.
        k: Number of document chunks to retrieve.

    Returns:
        Grounded answer generated by the Groq LLM.

    Raises:
        ValueError: If the question is empty.
    """
    if not question.strip():
        raise ValueError("Question can not be empty.")

    logger.info("Starting RAG query: %s", question)

    documents = retrieve_documents(query=question, k=k)

    if not documents:
        logger.warning("No relevent documents found for the query")
        raise ValueError("The annual report does not provide enough information to answer this.")

    context = build_context(documents)

    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(
            content=(
                f"Annual Report Context:\n\n"
                f"{context}\n\n"
                f"User Question:\n{question}"
            )
        ),
    ]

    response = llm.invoke(messages)

    logger.info("RAG answer generated successfully")

    return response.content